### ISSUE TITLE
Cmakelist - issues with toolchain settings and CMAKE_SYSTEM_NAME

### ISSUE THREAD

**Issue by 0xc0170** [arobenko/embxx_on_rpi#3] opened 2016-02-21 12:39 UTC
### CMAKE_SYSTEM_NAME

set (CMAKE_SYSTEM_NAME "RPi")

There's not information in readme. Shouldn't CMAKE_SYSTEM_NAME be Generic ? IF RPi is correct, how to fix this warning:

```
System is unknown to cmake, create:
Platform/RPi to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
```
### Toolchain file

It might be beneficial to provide toolchain file. Current cmake already contains some toolchain specific settings, however they are not multiplatform at the moment. I am using a machine with windows , where it fails:

```
-- Check for working C compiler: path/gcc_arm_5.2_2015q4/bin/arm-none-eabi-gcc.exe -- broken
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.5/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "path/gcc_arm_5.2_2015q4/bin/arm-none-eabi-gcc.exe"
  is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: path/embxx_on_rpi/build/CMakeFiles/CMakeTmp



  Run Build Command:"path/GnuWin32/make/bin/make.exe"
  "cmTC_5c37e/fast"

  path/GnuWin32/make/bin/make.exe -f
  CMakeFiles/cmTC_5c37e.dir/build.make CMakeFiles/cmTC_5c37e.dir/build

  make.exe[1]: Entering directory
  `path/embxx_on_rpi/build/CMakeFiles/CMakeTmp'

  Building C object CMakeFiles/cmTC_5c37e.dir/testCCompiler.c.obj

  path/gcc_arm_5.2_2015q4/bin/arm-none-eabi-gcc.exe -o
  CMakeFiles/cmTC_5c37e.dir/testCCompiler.c.obj -c
  path/embxx_on_rpi/build/CMakeFiles/CMakeTmp/testCCompiler.c

  Linking C executable cmTC_5c37e

 path/gcc_arm_5.2_2015q4/bin/arm-none-eabi-gcc.exe
  "CMakeFiles/cmTC_5c37e.dir/testCCompiler.c.obj" -o cmTC_5c37e


 path/gcc_arm_5.2_2015q4/bin/../lib/gcc/arm-none-eabi/5.2.1/../../../../arm-none-eabi/lib\libc.a(lib_a-exit.o):
  In function `exit':

  exit.c:(.text.exit+0x2c): undefined reference to `_exit'

  collect2.exe: error: ld returned 1 exit status

  make.exe[1]: *** [cmTC_5c37e] Error 1

  make.exe[1]: Leaving directory
  `C:/Code/github/embxx_on_rpi/build/CMakeFiles/CMakeTmp'

  make.exe: *** [cmTC_5c37e/fast] Error 2
```

To fix this, I added to the top:

```
include(CMakeForceCompiler)
cmake_force_c_compiler(arm-none-eabi-gcc GNU)
cmake_force_cxx_compiler(arm-none-eabi-g++ GNU)
```

However, this is causing a warning message with the cmake 3.5.0-rc2. Reference in cmake docs [here](https://cmake.org/cmake/help/v3.5/module/CMakeForceCompiler.html). It should be fine with older versions.. Any suggestions?

**Comment by arobenko** [comment] 2016-02-22 03:49
Yes, you are right, CMAKE_SYSTEM_NAME should be set to Generic.
Yes, introducing the toolchain files is a good idea. Try to create one for your system and pass it using 
-DCMAKE_TOOLCHAIN_FILE=... option to CMake. You'll have to modify existing main CMakeLists.txt to do the default operations of setting the compilers (c, c++, and as) in case the toolchain file wasn't specified. If your toolchain file works for you and you would like to commit it, make it generic, say "mingw on Windows" and put it to "toolchain" directory. We can update the README file with relevant information.

I suppose these changes should be developed on "develop" branch.

**Comment by ajneu** [comment] 2016-02-22 21:21
Hi there...

been following this discussion a bit.
Please add the following to the toplevel CMakeLists.txt:

``` cmake
set (CMAKE_AR           "${CROSS_COMPILE}ar")
set (CMAKE_RANLIB       "${CROSS_COMPILE}ranlib")
```

The difference will be noticable when compiling with `make VERBOSE=1`
Instead of `/usr/bin/ar` we then get `arm-none-eabi-ar`
instead of `/usr/bin/ranlib` we then get `arm-none-eabi-ranlib`

.
.
.
.
Regarding the toolchain... there's a lurking problem with newlib and its stubs...

-DCMAKE_TOOLCHAIN_FILE=... will call the toolchain definitions **before** the line 
`project ("embxx_on_rpi")` ([ref-link](https://github.com/arobenko/embxx_on_rpi/blob/be01e77c40d4cea679ac2a4a0f054f0f13449db6/CMakeLists.txt#L2))

People with with GNU/Linux (Alex, myself etc.) can mimic that (without needing to create a toolchain-file), by simply moving the line 

``` cmake
project ("embxx_on_rpi")
```

 ([ref-link](https://github.com/arobenko/embxx_on_rpi/blob/be01e77c40d4cea679ac2a4a0f054f0f13449db6/CMakeLists.txt#L2))
...down, to below the compiler definitions, e.g. to this line ([ref-link](https://github.com/arobenko/embxx_on_rpi/blob/be01e77c40d4cea679ac2a4a0f054f0f13449db6/CMakeLists.txt#L32))

The result will be quite horrible.

> Yes, you are right, CMAKE_SYSTEM_NAME should be set to Generic.

Yes this now becomes very evident, since we can now reproducibly get the reported error message:

> ```
> System is unknown to cmake, create:
> Platform/RPi to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
> ```

And there are also more warnings regarding the **stubs with newlib**.
There is possibly not a CMake solution for this yet. Check: https://cmake.org/Bug/view.php?id=15797 (in particular: [link](https://cmake.org/Bug/view.php?id=15797#c39641) etc.)

The **workaround**, would be to do something like an own toolchain-loading, which happens **after** the line
`project ("embxx_on_rpi")`

So my suggestion is: 

Change the `CMakeLists.txt` to something like this:

``` cmake
set (CMAKE_SYSTEM_NAME "Generic")    ## possibly put this in the else() branch... (I'm not certain)
set(toolchain   ""      CACHE FILEPATH     "")  ## -Dtoolchain=/my/path/to/toolchain_file
if (toolchain AND EXISTS ${toolchain})       ## -Dtoolchain=/my/path/to/toolchain_file
  message("==> Including toolchain_file ${toolchain}")
  include(${toolchain})
else()

  if ("${CROSS_COMPILE}" STREQUAL "")
    set (CROSS_COMPILE "arm-none-eabi-")
  endif()

  set (CMAKE_C_COMPILER   "${CROSS_COMPILE}gcc")
  set (CMAKE_CXX_COMPILER "${CROSS_COMPILE}g++")
  set (CMAKE_ASM_COMPILER "${CROSS_COMPILE}as")
  set (CMAKE_AR           "${CROSS_COMPILE}ar")
  set (CMAKE_RANLIB       "${CROSS_COMPILE}ranlib")

endif()
```

And then...: If you want to use a toolchain file, call cmake like this:
`cmake -Dtoolchain=/my/path/to/toolchain_file  /path/to/folder`

(Edited)

**Comment by arobenko** [comment] 2016-02-23 00:13
Good point, I'll merge your changes soon. I dislike the idea of having lower case variable names though, will use something like "-DCUSTOM_TOOLCHAIN=..."

**Comment by arobenko** [comment] 2016-02-23 07:26
The pull request is merged, README updated (on develop branch). Closing the issue.

**Closed as completed by arobenko** 2016-02-23 07:26 UTC
